// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM245uIgmwZQpOY_zVZERijXfMLu_rwf4',
    appId: '1:852861355814:web:45dc2b45748522f7e863e7',
    messagingSenderId: '852861355814',
    projectId: 'noti-5acf7',
    authDomain: 'noti-5acf7.firebaseapp.com',
    storageBucket: 'noti-5acf7.appspot.com',
    measurementId: 'G-M0N79FHRYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdKGgp8_nEe5AY2yRRqisiHiGfRjui0gA',
    appId: '1:852861355814:android:c0efba9e0658dc2de863e7',
    messagingSenderId: '852861355814',
    projectId: 'noti-5acf7',
    storageBucket: 'noti-5acf7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwQgW2YF_Bna3iUDSs8hMnbiUFFuysdIA',
    appId: '1:852861355814:ios:9ed3aab83bfbe746e863e7',
    messagingSenderId: '852861355814',
    projectId: 'noti-5acf7',
    storageBucket: 'noti-5acf7.appspot.com',
    iosBundleId: 'com.example.notification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwQgW2YF_Bna3iUDSs8hMnbiUFFuysdIA',
    appId: '1:852861355814:ios:9ed3aab83bfbe746e863e7',
    messagingSenderId: '852861355814',
    projectId: 'noti-5acf7',
    storageBucket: 'noti-5acf7.appspot.com',
    iosBundleId: 'com.example.notification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM245uIgmwZQpOY_zVZERijXfMLu_rwf4',
    appId: '1:852861355814:web:4449a0c396754ff9e863e7',
    messagingSenderId: '852861355814',
    projectId: 'noti-5acf7',
    authDomain: 'noti-5acf7.firebaseapp.com',
    storageBucket: 'noti-5acf7.appspot.com',
    measurementId: 'G-SYND45SLEC',
  );
}
